version: "0.0.1"
support: wgsl
resources:
  mvp_mat4:
    type: mat4
    mult: [wm_model_mat4, wm_view_mat4, wm_projection_mat4]
pipelines:
  terrain:
    geometry: wm_geo_terrain
    depth: wm_framebuffer_depth
    output: [wm_framebuffer_texture]
    uniforms:
      0: mvp_mat4
      1: wm_texture_atlas_blocks
  electrum_gui:
    geometry: wm_geo_electrum_gui
    output: [wm_framebuffer_texture]
    uniforms:
      0: mvp_mat4
      1: wm_electrum_gl_texture