version: "0.0.1"
support: wgsl
resources:
  mvp_mat4:
    type: mat4
    mult: [wm_mat4_projection, wm_mat4_view]
  shadow_depth:
    type: texture_depth
  shadow_col:
    type: texture_2d
  shadow_ortho_mat4:
    type: mat4
    value: [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
pipelines:
#  shadow_terrain:
#    geometry: wm_geo_terrain
#    depth: shadow_depth
#    output: []
#    uniforms:
#      0: mvp_mat4
  terrain:
    geometry: wm_geo_terrain
    depth: wm_framebuffer_depth
    output: [wm_framebuffer_texture]
    push_constants:
      0: wm_pc_chunk_position
      8: wm_pc_framebuffer_size
    uniforms:
      0: mvp_mat4
      1: wm_texture_atlas_blocks
      2: shadow_depth